name: OneSky Translation Sync

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write       # Required to create commits
  pull-requests: write  # Required to create pull requests

jobs:
  sync-translations:
    name: Sync with OneSky
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Sync translations with OneSky
        uses: onesky/public-actions@gha/sync-translations
        env:
          # Required: OneSky API credentials (add these as repository secrets)
          ONESKY_API_KEY: 'ce53446cec928ae01a7e2f2176a967fe'
          ONESKY_WORKSPACE_ID: 'd9bd145f-b51d-412c-b689-19309e9ab00d'
          ONESKY_PUBLIC_API_URL: 'https://api.oneskyhq-stag.com/v1'
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update translations from OneSky'
          title: '🌐 Update translations from OneSky'
          body: |
            ## 🌐 Translation Updates
            
            Automated translation sync from OneSky platform.
            
            ### Changes
            - ✅ Updated translation files
            - ✅ Synced with latest source content
            - ✅ Applied OneSky configuration from `.oneskyapp.yml`
            
            This pull request was automatically generated by the OneSky Translation Sync workflow.
          branch: 'onesky-translations'
          delete-branch: true
